name: flutter_line_liff_platform_interface
description: A Flutter package which define LINE LIFF SDK properties and methods.
version: 0.0.2
homepage: https://www.github.com/JimmyTai/flutter_line_liff

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0