name: flutter_line_liff_web
description: A Flutter package which support LINE LIFF SDK on Dart.
version: 1.0.0
homepage: https://www.github.com/JimmyTai/flutter_line_liff

environment:
  flutter: ">=3.22.0"
  sdk: ">=3.4.0 <4.0.0"

flutter:
  plugin:
    implements: flutter_line_liff
    platforms:
      web:
        pluginClass: FlutterLineLiffPlugin
        fileName: flutter_line_liff_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_line_liff_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0