name: flutter_line_liff_platform_interface
description: A Flutter package which define LINE LIFF SDK properties and methods.
version: 0.1.0
homepage: https://www.github.com/JimmyTai/flutter_line_liff

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.12.0"

dependencies:
  flutter:
    sdk: flutter
  js: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0